# http://travis-ci.org/#!/bollwyvl/hy_kernel
language: python
python:
  - 2.7
  - 3.4
sudo: false
cache:
  directories:
    - node_modules
    - $HOME/.pip-cache/
before_install:
  - npm install -g casperjs
  - phantomjs --version
  - casperjs --version
install:
  - pip install --download-cache $HOME/.pip-cache IPython[notebook] -r requirements-test.txt
  - python setup.py install
script:
  - flake8 setup.py hy_kernel
  - python setup.py nosetests
