# http://travis-ci.org/#!/bollwyvl/hy_kernel
language: python
python:
  - 2.7
  - 3.4
sudo: false
cache:
  directories:
    - node_modules
    - /home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages
    - /home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages
before_install:
  - npm install -g casperjs
  - phantomjs --version
  - casperjs --version
install:
  - pip install IPython[notebook]
  - pip install -r requirements-test.txt
  - python setup.py install
script:
  - flake8 setup.py hy_kernel
  - python setup.py nosetests
